apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django
        image: atmghan/django-ingress-demo:v2  # Use specific version
        ports:
        - containerPort: 8000
        env:
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DJANGO_SETTINGS_MODULE
          value: "app.settings"
        # Production-ready command:
        command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "app.wsgi:application"]
        # Add these for better management:
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10